[package]
name = "falcon-z3"
version = "0.3.1"
authors = ["Alex Eubanks <endeavor@rainbowsandpwnies.com>"]
homepage = "https://github.com/falconre/falcon_z3"
repository = "https://github.com/falconre/falcon_z3"
description = "Rust bindings for z3 and Falcon"
readme = "README.md"
license = "MIT"
build = "build.rs"

[dependencies]
error-chain = "0.11"
falcon = { version="0.3.1", features=["thread_safe"] }
num-bigint = { version="0.2", features = ["serde"]}
num-traits = "0.2.1"

[lib]
name = "falcon_z3"
path = "lib/lib.rs"

[build-dependencies]
bindgen = "0.35.0"