on: [push, pull_request]
name: All Checks
jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget build-essential llvm clang libclang-dev libz3-dev
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - name: cargo test
        run: cargo test
      - name: cargo fmt
        run: cargo fmt --all -- --check
      - name: cargo clippy
        run: cargo clippy -- -D warnings
